name: Build & Push Docker (GHCR)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    # permite publicar no GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image meta
        id: meta
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository }}/taskflow" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "TAG_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "TAG_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_SHORT }}
            ${{ steps.meta.outputs.IMAGE }}:${{ steps.meta.outputs.TAG_BRANCH }}
            ${{ steps.meta.outputs.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
