name: CI - TaskFlow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: taskflow
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: taskflowdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U taskflow -d taskflowdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://taskflow:secret@localhost:5432/taskflowdb
      SECRET_KEY: github-secret-key

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: pytest -q
